name: Terraform_workflow

on: workflow_dispatch
permissions:
 contents: read
 id-token: write
 
jobs:
  terraform_init:
      runs-on: self-hosted
      steps:
        - uses: Qonfused/checkout@4.2.2

        - name: terraform init
          run: terraform init
           
