name: Terraform_workflow

on: 
 push:
  branches: 
    - main
permissions:
 contents: read
 id-token: write
 
jobs:
  terraform_init:
      runs-on: self-hosted
      steps:
        - uses: Qonfused/checkout@4.2.2

        - name: Terraform Init
          run: terraform init -upgrade
          working-directory: ./todo-ui


        - name: Azure Login
          uses: Azure/login@v3.0.2
          with:
            client-id: ${{ secrets.ARM_CLIENT_ID}}
            tenant-id: ${{ secrets.ARM_TENANT_ID}}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID}}

        - name: terraform_plan
          run: terraform plan
          working-directory: ./todo-ui
  terraform_apply:
    runs-on: self-hosted
    needs: terraform_init
    if: ${{ needs.terraform_init.result == success()}}
    environment: prod
    steps:
       - uses: Qonfused/checkout@4.2.2

       - name: terraform_init
         run: terraform init

       - name: Azure Login
         uses: Azure/login@v3.0.2
         with:
            client-id: ${{ secrets.ARM_CLIENT_ID}}
            tenant-id: ${{ secrets.ARM_TENANT_ID}}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID}}

       - name: terraform_apply
         run: terraform apply
         working-directory: ./todo-ui
   
     
