name: Terraform_workflow

on: workflow_dispatch

jobs:
  terraform_init:
    - name: terraform_init
      runs-on: self-hosted
      steps:
        - name: Checkout-388
          # You may pin to the exact commit or the version.
          # uses: Qonfused/checkout@ef23884d4741c3aea52577aaaf81a3849aeeac05
           uses: Qonfused/checkout@4.2.2

        - name: terraform init
          run: terraform init
           
