name: terraform infra pipeline
on: 
  workflow_dispatch:
permissions:  
  id-token: write
  contents: read
jobs:
  terraforminitandplan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: 10ec7e79-3893-49b8-aefc-5451bc1fffc1
          tenant-id: 23caa587-9951-4fb9-8847-7bc506258a2d
          subscription-id: 5d297d85-ddad-4ac7-8baa-2ce25e3f0ce5

 
    
  
